source 'https://rubygems.org'

gem 'trollop'
gem 'pry'
gem 'selenium-webdriver'
gem 'mail'
gem 'sudo'
gem 'google-api-client'
gem 'sinatra'
gem 'thin'
gem 'tilt'
gem 'sinatra-contrib'
gem 'backports'
gem 'erubis'
